services:
    mysql:
        image: mysql/mysql-server:latest
        container_name: mysql

        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: coderhouse
            MYSQL_ROOT_HOST: 127.0.0.1
        
        volumes:
            - ./workspace:/workspace
            - ./mysql/my.cnf:/etc/mysql/my.cnf
